version: "3"

volumes:
  postgres:

services:
  postgres:
    image: postgres:13.4-buster
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: customer
    ports:
      - "9999:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
